### ISSUE TITLE
v 测试模板文件的功能

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/duyu#12]
1

**Comment by vieyahn2017** [comment]
0.yaml

```yaml
choices:
 clouds: ["spotted", "thick", "pendulous", "mackerel"]
 sun: ["bright", "grey", "warm", "thin"]
 wind: ["gusting", "cool", "breezy", "strong"]
 temperature: ["cold", "cool", "mild", "warm", "hot"]

schemas:
 weather: ["{{ clouds }} clouds with {{ wind }} wind", 
  "it's {{ temperature }}", 
  "the sun is {{ sun }}, with {{ clouds }} clouds"
]
```
